routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



// DaySheet Routes
Route::resource('/daysheets','DaySheetController');



// ExpenseTransaction Routes
Route::resource('/expense_transaction','ExpenseTransactionController');

Route::prefix('admin')->group(function () {
        Route::resource('/chem_types', 'Admin\ChemTypesController');
        Route::resource('/expense_category','Admin\ExpenseCategoryController');
        Route::resource('/chem_sale_price','Admin\ChemSalePriceController');
});

Route::prefix('accounts')->group(function () {
      Route::resource('/daily_profit','Accounts\DailyProfitController');
});

Route::prefix('transactions')->group(function () {
      Route::resource('/purchase_invoices','Transactions\PurchaseInvoiceController');
});

app/Http/Controllers/Admin/ChemTypesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Admin\ChemType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\User;

class ChemTypesController extends \App\Http\Controllers\Controller
{
    public function __construct()
    {
         $this->middleware('auth');
     }


    public function index()
    {
      $userChemTypesCount = chem_type_count();


      $userChemTypeArray = create_chem_type_array();

      return view('admin.chem_types.index', [
              'userChemTypesCount' => $userChemTypesCount,
              'userChemTypeArray' => $userChemTypeArray,

            ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
        'chem_type_name.0' => 'required_without_all:chem_type_name.*',
      ]);

      $result = create_chem_type_db($request->chem_type_name);
      return redirect('admin/chem_types')->with('status', 'Chemical Types created!');


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ChemType  $chemType
     * @return \Illuminate\Http\Response
     */
    public function show(ChemType $chemType)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ChemType  $chemType
     * @return \Illuminate\Http\Response
     */
    public function edit(ChemType $chemType)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ChemType  $chemType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ChemType $chemType)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ChemType  $chemType
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $chemTypeFirst = DB::table('chem_types')->where([
                              ['user_id', '=', Auth::id()],
                              ['id', '=', $id]  ])->first();

      if($chemTypeFirst->day_sheet_id != null) {
        return redirect('admin/chem_types')
            ->with('status', 'Chemical Types cannot be deleted, there are sales attached!');
          }



        DB::table('chem_types')->where([
                ['user_id', '=', Auth::id()],
                ['id', '=', $id],
                            ])->delete();
      return redirect('admin/chem_types')
              ->with('status', 'Chemical Type deleted!');
    }
}

resources/views/admin/chem_types/index.blade.php
@extends('layouts.main')

@section('content')

<div class="content-wrapper">

  <section class="content-header">
    <h4>Create Chemical Type</h4>
    @include('partials.errors')
          <div class="maxChemicalTypesError" id="maxChemicalTypesError">
          </div>
    <ol class="breadcrumb">
      <li class="active"><i class="fa fa-dashboard"></i>Settings</li>
    </ol>
  </section>
<div class="panel panel-info">

<div class="panel-body">

  <div class="panel panel-info">
            <div class="panel-heading"><h4>Chemical Type Name</h4></div>
      <div class="panel-body">
                <form action="{{ route('chem_types.store') }}" method="post">
                       {{ csrf_field() }}
<table>
                       <div class="fieldGroup">
                         <div class="row">
                       <div class="form-group col-lg-4">
                             <label for="name">Name</label>
                             <input type="text" name="chem_type_name[]" class="form-control">
                       </div>
                       <div class="form-group col-lg-4">
                             <label for="name">Name</label>
                             <input type="text" name="chem_type_name[]" class="form-control">
                       </div>
                       <div class="col-lg-2" style="margin-top:25px;">
                       <a href="javascript:void(0)" class="btn btn-danger addMore">
                         <span class="glyphicon glyphicon glyphicon-remove" aria-hidden="true">
                         </span> Add
                       </a>
                       </div>
                       </div>
                       </div>
</table>


                       <!-- <div class="row"> -->
                       <div class="form-group col-lg-8" style="margin-top:25px;">
                       <!-- <div class="form-group col-lg-8"> -->
                             <div class="text-center">
                                   <button class="btn btn-success" type="submit">
                                         Save
                                   </button>
                             </div>
                       </div>
                       <!-- </div> -->
                 </form>
           </div>
           </div>
<!-- ///////////////////LIST -->
           <div class="panel panel-info">
                     <div class="panel-heading"><h4>Chemical Type List</h4></div>
               <div class="panel-body">



                  <table class="table table-hover">
        @if($userChemTypesCount > 0)
                        <thead>
                              <th>
                                DaySheet
                              </th>
                                    <th>{{ "Chemical " }}</th>
                        </thead>
                        <tbody>
                          @foreach($userChemTypeArray as $chem)
                                      <tr>

                                        <td>{{ $chem->chem_type_user['id'] }}  </td>


                                        <td>{{ $chem->chem_name }}  </td>
                            <td>
                                  <form action="{{ route('chem_types.destroy' , ['id' => $chem->id])  }}" method="POST">
                                        <input name="_method" type="hidden" value="DELETE">
                                        {{ csrf_field() }}
                                            <button type="submit" class="btn btn-xs btn-danger">Delete</button>
                                  </form>
                            </td>
                                                              </tr>
                              @endforeach
                        </tbody>
          @endif
@empty ($userChemTypesCount)
<tr>
     <th colspan="9" class="text-center">No Chemical Type Saved
       <div class="btn btn-xs btn-info">
         Create New Chemical Type
       </div>
     </th>
</tr>
@endempty
                  </table>

            </div>
      </div>
      </div>
      </div>

      <div class="fieldGroupCopy"  style="display: none;">
        <div class="row">
      <div class="form-group col-lg-4">
            <input type="text" name="chem_type_name[]" class="form-control">
      </div>
      <div class="form-group col-lg-4">
            <input type="text" name="chem_type_name[]" class="form-control">
      </div>
      <div class="col-lg-2">
      <a href="javascript:void(0)" class="btn btn-danger remove">
        <span class="glyphicon glyphicon glyphicon-remove" aria-hidden="true">
        </span> Remove
      </a>
      </div>
      </div>
      </div>

      <script type="text/javascript">
      $(document).ready(function(){
          var maxGroup = 5;
          var totalChemicalTypes = maxGroup * 2;
          var oneAlertMsg = 0;

          $(".addMore").click(function(e){
              if($('body').find('.fieldGroup').length < maxGroup){
                  var fieldHTML = '<div class="fieldGroup">'+$(".fieldGroupCopy").html()+'</div>';
                  $('body').find('.fieldGroup:last').after(fieldHTML);
              }else{
                  if(oneAlertMsg == 0){
                        alertMsg = 'Maximum '+totalChemicalTypes+' Chemical Types are allowed.';
                        $('body').find('.maxChemicalTypesError').after(alertMsg);
                        ++oneAlertMsg;
                        }
              }
          });


          //remove fields group
          $("body").on("click",".remove",function(){
              $(this).parents(".fieldGroup").remove();
          });


      });
      </script>
@endsection