routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



// DaySheet Routes
Route::resource('/daysheets','DaySheetController');



// ExpenseTransaction Routes
Route::resource('/expense_transaction','ExpenseTransactionController');

Route::prefix('admin')->group(function () {
        Route::resource('/chem_types', 'Admin\ChemTypesController');
        Route::resource('/expense_category','Admin\ExpenseCategoryController');
        Route::resource('/chem_sale_price','Admin\ChemSalePriceController');
});

Route::prefix('accounts')->group(function () {
      Route::resource('/daily_profit','Accounts\DailyProfitController');
});

Route::prefix('transactions')->group(function () {
      Route::resource('/purchase_invoices','Transactions\PurchaseInvoiceController');
});

app/Models/DaySheet.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DaySheet extends Model
{
    protected $fillable = [
         'daysheet_date',
        'daily_sales_total', 'daily_revenue_total', 
        'daily_expenses_total',
        ];

    public function ds_dailysales()
    {
        return $this->hasOne('App\Models\Transaction\DailySale' );
    }
    public function ds_dailystocks()
    {
        return $this->hasOne('App\Models\Transaction\DailyStock' );
    }
    public function ds_chemtypes()
    {
        return $this->hasMany('App\Models\Admin\ChemType' );
    }
}

app/Http/Controllers/DaySheetController.php
<?php

namespace App\Http\Controllers;

use App\Models\Admin\ChemType;
use App\Models\Admin\ExpenseCategory;
use App\Models\DaySheet;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\User;

class DaySheetController extends Controller
{
    public function __construct()
    {
       $this->middleware('auth');
    }

    public function index()
    {
      $daySheetCount = day_sheet_count();

      $daySheetColl = create_daysheet_array();

      $lastDaySheetID = last_day_sheet_id();

      $userChemNameArray = create_chem_type_name_array();
      $chemTypeCount = chem_type_count();

        return view('daysheets.index', [
                'daySheetCount' => $daySheetCount,
                'day_sheets' => $daySheetColl,
                'daysheetCount' => $daySheetCount,
                'lastDaySheetID' => $lastDaySheetID,
                'userChemNameArray' => $userChemNameArray,
                'chemTypeCount' => $chemTypeCount,
              ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

      $userChemTypeCount  = chem_type_count();
      if($userChemTypeCount == 0){
        return view('home');
      }      
      /////////////////Expenses Drop down
            $catCount = DB::table('expense_categories')->where('user_id', Auth::id())
                            ->count();
            $userexpCatColl = ExpenseCategory::where('user_id', Auth::id())
                                        ->orderBy('id', 'desc')->get();
              if(!empty($expCatCount)){
            $userExpenseCategories = create_expense_category_array($userexpCatColl);
                  }   else {
                    $userExpenseCategories = array_fill(0, 10, null);
                  }



      $userChemTypeStockCount  = chem_type_stock_count();
      $userChemTypeNameArray = create_chem_type_name_array();
      $userChemTypeStockArray = create_chem_type_stock_array();


        return view('daysheets.create', [
                'userChemTypeNameArray' => $userChemTypeNameArray,
                'userChemTypeStockArray' => $userChemTypeStockArray,
                'userChemTypeCount' => $userChemTypeCount,
                'userChemTypeStockCount' => $userChemTypeStockCount,
                'catCount' => $catCount,
                'categories' => $userExpenseCategories,
              ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
          'chem_type_sale.*' => 'required|numeric',
          'ds_date' => 'required',
      ]);



      $newDaySheet = create_daysheet_db($request->ds_date);

      $reqSaleArray = create_req_array($request->chem_type_sale);
      $newSales = create_sales_db($reqSaleArray, $newDaySheet);
      create_chem_type_foreignKey($newDaySheet);

      $reqStockArray = create_req_array($request->chem_type_stock);
      $newStocks = create_stocks_db($reqStockArray, $newDaySheet);

      return redirect('daysheets')->with('status', 'Day Sheet created!');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\DaySheet  $daySheet
     * @return \Illuminate\Http\Response
     */
    public function show(DaySheet $daySheet)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\DaySheet  $daySheet
     * @return \Illuminate\Http\Response
     */
    public function edit(DaySheet $daySheet)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\DaySheet  $daySheet
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, DaySheet $daySheet)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\DaySheet  $daySheet
     * @return \Illuminate\Http\Response
     */
    public function destroy(DaySheet $daySheet)
    {
        //
    }
}

resources/views/daysheets/create.blade.php
@extends('layouts.main')

@section('content')

<div class="content-wrapper">
    <section class="content-header">
      <h4>
      Create New Day Sheet
    </h4>
      @include('partials.errors')
            <div class="jqry_Error" id="jqry_Error">
            </div>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>DaySheet</li>
      </ol>
    </section>

    <div class="panel panel-info">
      <div class="panel-body">

      <!-- Table -->
      <form method="post" action="{{ route('daysheets.store') }}">
    {{ csrf_field() }}

        <div class="panel panel-info">
              <div class="panel-heading"><h4>Sales and Stock</h4></div>
              <div class="panel-body">
                @include('daysheet_partials.create_textfields')
              </div>
        </div>

        <!-- /////////////////EXPENSES/////////////////////// -->
      @include('daysheet_partials.ds_expenses')


</div>
          <button type="submit" class="btn btn-primary">Save New Day Sheet</button>
</form>
</div>
<!-- </wrapper> -->
</div>
</div>
<!-- /////////////////////////////////////////////////////////////// -->

@include('daysheet_partials.fieldGroupCopy')
@include('daysheet_partials.js_daysheet')
@endsection

resources/views/daysheets/index.blade.php
@extends('layouts.main')

@section('content')



<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
    DaySheet List
  </h1>&nbsp;
    @include('partials.errors')
    <ol class="breadcrumb">
      <li class="active"><i class="fa fa-dashboard"></i>Dashboard</li>
    </ol>
  </section>

<!-- Main content -->
<section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <!-- /.box-header -->
          <div class="box-body ">
            <div class="table-responsive">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th scope="col"></th>
                    <th scope="col">Date</th>
                    @for($e=0; $e < $chemTypeCount; $e++)
                    <th scope="col">{{ $userChemNameArray[$e] }}</th>
                    @endfor
                    <th scope="col">Expenses</th>
                    <th scope="col">HR</th>


                  </tr>
                </thead>
                <tbody>
<!-- check if categories exist -->
            @empty($chemTypeCount)
            <tr>


                 <th colspan="12" class="text-center">No Chemical Types Saved.
                   <a href="{{ route('chem_types.index') }}" class="btn btn-xs btn-info">
                     Create New Chemical Types
                   </a>
                 </th>
            </tr>
            @endempty




   <!-- check if day sheets exist -->
                      @if(!empty($daysheetCount))

                            @php
                              $rowcount = 1;
                            @endphp
                          @foreach($day_sheets as $day_sheet)
                      <tr>
                        <th scope="row">
                            @php
                              echo $rowcount++
                            @endphp
                        </th>
                        <td>{{ $day_sheet->daysheet_date }}</td>
                        <td>{{ $day_sheet->id }}</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>{{ $day_sheet->expenses_total }}</td>

                        <td>

                        @if ($day_sheet->id == $lastDaySheetID)
                          <a href="{{ route('daysheets.edit', ['id' => $day_sheet->id ]) }}" class="btn btn-xs btn-info">
                                Edit
                          </a>
                          <form action="{{ route('daysheets.destroy' , ['id' => $day_sheet->id ])  }}" method="POST">
                                <input name="_method" type="hidden" value="DELETE">
                                {{ csrf_field() }}
                                    <button type="submit" class="btn btn-xs btn-danger">Delete</button>
                          </form>
                          <a href="{{ route('daysheets.show', ['id' => $day_sheet->id ]) }}" class="btn btn-xs btn-primary">
                                View
                          </a>
                           @else
                           <a href="{{ route('daysheets.show', ['id' => $day_sheet->id ]) }}" class="btn btn-xs btn-primary">
                                 View
                           </a>
                          @endif
                        </td>
                      </tr>
                          @endforeach
                      @endif

                </tbody>
              </table>
              </div>
              </div>
              <!-- /.box-body -->
            </div>
            <!-- /.box -->
          </div>
            <!-- /.col-xs-12 -->
        </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->


            <!-- </div> -->
            </div>
            <!-- </div> -->
        <!-- </div>
        </div> -->
@endsection