routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



// DaySheet Routes
Route::resource('/daysheets','DaySheetController');



// ExpenseTransaction Routes
Route::resource('/expense_transaction','ExpenseTransactionController');

Route::prefix('admin')->group(function () {
        Route::resource('/chem_types', 'Admin\ChemTypesController');
        Route::resource('/expense_category','Admin\ExpenseCategoryController');
        Route::resource('/chem_sale_price','Admin\ChemSalePriceController');
});

Route::prefix('accounts')->group(function () {
      Route::resource('/daily_profit','Accounts\DailyProfitController');
});

Route::prefix('transactions')->group(function () {
      Route::resource('/purchase_invoices','Transactions\PurchaseInvoiceController');
});

app/Models/Admin/ExpenseCategory.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;

class ExpenseCategory extends Model
{
  protected $fillable = [
    'expense_category_name',
  ];

    public function expense_transactions()
    {
        return $this->belongsTo('App\Models\Admin\ExpenseTransaction');

    }
    public function expcat_user()
    {
        return $this->belongsTo('App\User');

    }
}

app/Http/Controllers/Admin/ExpenseCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Admin\ExpenseCategory;
use App\Models\Admin\ChemType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\User;

class ExpenseCategoryController extends \App\Http\Controllers\Controller
{

    public function __construct()
    {
         $this->middleware('auth');

     }

    public function index()
    {
      $userExpCatCount = expense_category_count();


      $userExpCatArray = create_expense_category_array();

      return view('admin.expense_category.index', [
              'userExpCatCount' => $userExpCatCount,
              'userExpCatArray' => $userExpCatArray,

            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
      'exp_cat_name.0' => 'required_without_all:exp_cat_name.*',

      ]);

      $result = create_expense_category_db($request->exp_cat_name);

            return redirect('admin/expense_category')->with('status', 'Category created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ExpenseCategory  $expenseCategory
     * @return \Illuminate\Http\Response
     */
    public function show(ExpenseCategory $expenseCategory)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ExpenseCategory  $expenseCategory
     * @return \Illuminate\Http\Response
     */
    public function edit(ExpenseCategory $expenseCategory)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ExpenseCategory  $expenseCategory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ExpenseCategory $expenseCategory)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ExpenseCategory  $expenseCategory
     * @return \Illuminate\Http\Response
     */
    public function destroy(ExpenseCategory $expenseCategory)
    {
        //
    }
}

resources/views/admin/expense_category/index.blade.php
@extends('layouts.main')

@section('content')

<div class="content-wrapper">

  <section class="content-header">
    <h4>Create Expense Categories</h4>
    @include('partials.errors')
          <div class="maxExpCatError" id="maxExpCatError">
          </div>
    <ol class="breadcrumb">
      <li class="active"><i class="fa fa-dashboard"></i>Settings</li>
    </ol>
  </section>
<div class="panel panel-info">
  <!-- <div class="panel-heading"><h4>Create Chem Type</h4></div> -->

<div class="panel-body">

  <div class="panel panel-info">
            <div class="panel-heading"><h4>Expense Category Name</h4></div>
      <div class="panel-body">
                <form action="{{ route('expense_category.store') }}" method="post">
                       {{ csrf_field() }}
<table>
                       <div class="fieldGroup">
                         <div class="row">
                       <div class="form-group col-lg-4">
                             <label for="name">Name</label>
                             <input type="text" name="exp_cat_name[]" class="form-control">
                       </div>
                       <div class="form-group col-lg-4">
                             <label for="name">Name</label>
                             <input type="text" name="exp_cat_name[]" class="form-control">
                       </div>
                       <div class="col-lg-2" style="margin-top:25px;">
                       <a href="javascript:void(0)" class="btn btn-danger addMore">
                         <span class="glyphicon glyphicon glyphicon-remove" aria-hidden="true">
                         </span> Add
                       </a>
                       </div>
                       </div>
                       </div>
</table>


                       <!-- <div class="row"> -->
                       <div class="form-group col-lg-8" style="margin-top:25px;">
                       <!-- <div class="form-group col-lg-8"> -->
                             <div class="text-center">
                                   <button class="btn btn-success" type="submit">
                                         Create
                                   </button>
                             </div>
                       </div>
                       <!-- </div> -->
                 </form>
           </div>
           </div>

           <div class="panel panel-info">
                     <div class="panel-heading"><h4>Expense Categories List</h4></div>
               <div class="panel-body">


                     <table class="table table-hover">
           @if($userExpCatCount > 0)
                           <thead>
                                 <th>
                                  ID
                                 </th>
                           </thead>
                           <tbody>
               @foreach($userExpCatArray as $cat)
                           <tr>
                       <td>{{ $loop->index }}{{ "- ".$cat->expense_category_name }}</td>
                 <td>
                         <form action="{{ route('expense_category.destroy' , ['id' => $cat->id])  }}" method="POST">

                             <input name="_method" type="hidden" value="DELETE">
                             {{ csrf_field() }}
                                 <button type="submit" class="btn btn-xs btn-danger">Delete</button>
                       </form>
                 </td>
                                                   </tr>
                   @endforeach
                           </tbody>
             @endif
   @empty ($userExpCatCount)
   <tr>
        <th colspan="9" class="text-center">No Expense Categories Saved
          <div class="btn btn-xs btn-info">
            Create New Expense Categories
          </div>
        </th>
   </tr>
   @endempty
                     </table>

               </div>

            </div>
      </div>
      </div>
      </div>

      <div class="fieldGroupCopy"  style="display: none;">
        <div class="row">
      <div class="form-group col-lg-4">
            <!-- <label for="name">Name</label> -->
            <input type="text" name="exp_cat_name[]" class="form-control">
      </div>
      <div class="form-group col-lg-4">
            <!-- <label for="name">Name</label> -->
            <input type="text" name="exp_cat_name[]" class="form-control">
      </div>
      <div class="col-lg-2">
      <a href="javascript:void(0)" class="btn btn-danger remove">
        <span class="glyphicon glyphicon glyphicon-remove" aria-hidden="true">
        </span> Remove
      </a>
      </div>
      </div>
      </div>

      <script type="text/javascript">
      $(document).ready(function(){
          //group add limit
          var maxGroup = 5;
          var totalChemTypes = maxGroup * 2;
          var oneAlertMsg = 0;

          //add more fields group
          $(".addMore").click(function(e){
              if($('body').find('.fieldGroup').length < maxGroup){
                  var fieldHTML = '<div class="fieldGroup">'+$(".fieldGroupCopy").html()+'</div>';
                  $('body').find('.fieldGroup:last').after(fieldHTML);
              }else{
                  if(oneAlertMsg == 0){
                        alertMsg = 'Maximum '+totalChemTypes+' expense categories are allowed.';
                        $('body').find('.maxExpCatError').after(alertMsg);
                        ++oneAlertMsg;
                        }
              }
          });
          //add more fields group
          $(".addMore1").click(function(e){
              if($('body').find('.fieldGroup1').length < maxGroup){
                  var fieldHTML = '<div class="fieldGroup1">'+$(".fieldGroupCopy1").html()+'</div>';
                  $('body').find('.fieldGroup1:last').after(fieldHTML);
              }else{
                  alert('Maximum '+maxGroup+' expense categories are allowed.');
              }
          });

          //remove fields group
          $("body").on("click",".remove",function(){
              $(this).parents(".fieldGroup").remove();
          });

          $("body").on("click",".remove1",function(){
              $(this).parents(".fieldGroup1").remove();
          });

      });
      </script>
@endsection